### Loguearse
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "bryan2",
    "password": "123456"
}


### Registrar un Usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "bryan3",
    "password": "123456"
}
