### Obtener todas las peliculas
GET http://localhost:3000/movies


### Filtrar por genero
GET http://localhost:3000/movies?genre=Action


### Buscar pelicula por ID
GET http://localhost:3000/movies/bf6a4a92-ced1-11ef-8e5f-98e743135570


### Crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Nueva Pelicula 2",
    "year": 1993,
    "director": "Lana Wachowski",
    "duration": 136,
    "poster": "https://i.ebayimg.com/images/g/QFQAAOSwAQpfjaA6/s-l1200.jpg",
    "genre": [
      "Action",
      "Sci-Fi"
    ]

}

### Eliminar una pelicula
DELETE http://localhost:3000/movies/0b7bd27f-cef2-11ef-a19b-98e743135570

### Actualizar la informacion de una pelicula
PATCH http://localhost:3000/movies/ddec4525-cef0-11ef-a19b-98e743135570
Content-Type: application/json

{
  "year": 1981
}

